### ISSUE TITLE
Thesis Topics

### ISSUE THREAD

**Issue by rjesteban** [arnellebalane/ama#9]
Can you mention some interesting thesis topics? and, is it still too early to think about a thesis topic?

**Comment by arnellebalane** [comment]
I think there's no such such thing as "too early to think about a thesis topic". So that you don't have a lot of problems when school starts again, I suggest you start thinking about what you want to do for your thesis as soon as possible (e.g. think of possible topics, choose your adviser and talk to him/her already, etc.). It is also important to choose your adviser properly, make sure that their specialties align with your thesis topic.

Now about interesting thesis topics, hmmm. I can't think of specific topics at the top of my head but here are some ideas that might help guide you to a good thesis topic:
- Machine learning seems to be the popular thing these days, so doing a thesis about it is definitely an awesome thing (but make sure your topic is doable within the available time where you can work on it). There are a lot of tools out there for machine learning (e.g. TensorFlow, Google Cloud Machine Learning tools, Microsoft Cognitive Services, etc.) that are super useful for doing machine learning studies, so try to think of a real-life problem wherein you can apply machine learning using those tools to solve them.
- Bots. I don't know what study can be conducted about bots but they sound interesting.

That's all I can think for now. Maybe @jedijulia has some more ideas :smile:
